# Hierarchical model
This exemple shows how the hierarchical model can be used

In [1]:
import sys
sys.path.append('../')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
%matplotlib inline  

from gtime.hierarchical import HierarchicalMiddleOut
from gtime.hierarchical import HierarchicalTopDown
from gtime.hierarchical import HierarchicalBottomUp
import pandas._testing as testing
from gtime.time_series_models import AR

In [3]:
testing.N, testing.K = 20, 1

data1 = testing.makeTimeDataFrame(freq="s")
data2 = testing.makeTimeDataFrame(freq="s")
data3 = testing.makeTimeDataFrame(freq="s")
data4 = testing.makeTimeDataFrame(freq="s")
data5 = testing.makeTimeDataFrame(freq="s")
data6 = testing.makeTimeDataFrame(freq="s")
data = {'data1': data1, 'data2': data2, 'data3' : data3, 'data4' : data4, 'data5' : data5, 'data6' : data6}

In [4]:
tree_adj = {'data1' : ['data2','data3'], 'data2': ['data4', 'data5'], 'data3':['data6'], 'data4':[], 'data5':[], 'data6':[]}

In [5]:
stat_model = AR(p=2, horizon=3)
middle_out_model = HierarchicalMiddleOut(model=stat_model, hierarchy_tree=tree_adj, method='tdsga', level=0)

Pass n_jobs=None as keyword args. From version 0.25 passing these as positional arguments will result in an error

In [6]:
fitting_middle_out = middle_out_model.fit(data)

AR(horizon=3, p=2)

In [7]:
fitting_middle_out.predict(data)

{'data1':                           y_1       y_2       y_3
 2000-01-01 00:00:01 -0.158229 -0.108937  0.013279
 2000-01-01 00:00:02 -0.119528 -0.059880 -0.107075
 2000-01-01 00:00:03 -0.045503  0.021338  0.047517
 2000-01-01 00:00:04  0.012864  0.096452 -0.168450
 2000-01-01 00:00:05 -0.151905 -0.096779 -0.132723
 2000-01-01 00:00:06  0.069999  0.150488  0.214797
 2000-01-01 00:00:07  0.001033  0.093826 -0.508995
 2000-01-01 00:00:08 -0.568503 -0.583920 -0.085755
 2000-01-01 00:00:09 -0.457690 -0.464454  0.210157
 2000-01-01 00:00:10 -0.122242 -0.067394  0.025629
 2000-01-01 00:00:11 -0.118071 -0.056340 -0.163261
 2000-01-01 00:00:12 -0.191902 -0.147248 -0.015386
 2000-01-01 00:00:13 -0.294175 -0.260952 -0.183406
 2000-01-01 00:00:14 -0.181954 -0.143633  0.228090
 2000-01-01 00:00:15 -0.045477  0.031479 -0.260897
 2000-01-01 00:00:16 -0.226103 -0.186952 -0.020310
 2000-01-01 00:00:17 -0.601745 -0.612361 -0.400169
 2000-01-01 00:00:18 -0.775542 -0.839130  0.337599
 2000-01-01 00:00:19 -0.330639 -0.312211  0.083676,
 'data2':                           y_1       y_2       y_3
 2000-01-01 00:00:01  0.270159  0.185998 -0.022672
 2000-01-01 00:00:02  0.204081  0.102239  0.182818
 2000-01-01 00:00:03  0.077691 -0.036433 -0.081129
 2000-01-01 00:00:04 -0.021964 -0.164682  0.287609
 2000-01-01 00:00:05  0.259361  0.165239  0.226610
 2000-01-01 00:00:06 -0.119516 -0.256941 -0.366741
 2000-01-01 00:00:07 -0.001764 -0.160198  0.869053
 2000-01-01 00:00:08  0.970656  0.996979  0.146418
 2000-01-01 00:00:09  0.781456  0.793004 -0.358821
 2000-01-01 00:00:10  0.208715  0.115068 -0.043758
 2000-01-01 00:00:11  0.201593  0.096194  0.278750
 2000-01-01 00:00:12  0.327652  0.251409  0.026269
 2000-01-01 00:00:13  0.502271  0.445547  0.313145
 2000-01-01 00:00:14  0.310666  0.245238 -0.389439
 2000-01-01 00:00:15  0.077647 -0.053747  0.445453
 2000-01-01 00:00:16  0.386045  0.319200  0.034676
 2000-01-01 00:00:17  1.027413  1.045538  0.683245
 2000-01-01 00:00:18  1.324152  1.432722 -0.576413
 2000-01-01 00:00:19  0.564529  0.533066 -0.142867,
 'data4':                           y_1       y_2       y_3
 2000-01-01 00:00:01 -0.290519 -0.200016  0.024381
 2000-01-01 00:00:02 -0.219461 -0.109944 -0.196596
 2000-01-01 00:00:03 -0.083546  0.039178  0.087243
 2000-01-01 00:00:04  0.023619  0.177093 -0.309285
 2000-01-01 00:00:05 -0.278907 -0.177692 -0.243688
 2000-01-01 00:00:06  0.128523  0.276306  0.394381
 2000-01-01 00:00:07  0.001897  0.172271 -0.934548
 2000-01-01 00:00:08 -1.043809 -1.072116 -0.157453
 2000-01-01 00:00:09 -0.840350 -0.852768  0.385863
 2000-01-01 00:00:10 -0.224444 -0.123740  0.047056
 2000-01-01 00:00:11 -0.216786 -0.103444 -0.299757
 2000-01-01 00:00:12 -0.352345 -0.270357 -0.028249
 2000-01-01 00:00:13 -0.540124 -0.479125 -0.336745
 2000-01-01 00:00:14 -0.334079 -0.263720  0.418789
 2000-01-01 00:00:15 -0.083499  0.057797 -0.479024
 2000-01-01 00:00:16 -0.415140 -0.343256 -0.037290
 2000-01-01 00:00:17 -1.104843 -1.124335 -0.734737
 2000-01-01 00:00:18 -1.423946 -1.540698  0.619854
 2000-01-01 00:00:19 -0.607074 -0.573241  0.153634,
 'data5':                           y_1       y_2       y_3
 2000-01-01 00:00:01 -0.391357 -0.269440  0.032843
 2000-01-01 00:00:02 -0.295635 -0.148105 -0.264833
 2000-01-01 00:00:03 -0.112545  0.052777  0.117525
 2000-01-01 00:00:04  0.031817  0.238561 -0.416636
 2000-01-01 00:00:05 -0.375714 -0.239368 -0.328271
 2000-01-01 00:00:06  0.173133  0.372210  0.531268
 2000-01-01 00:00:07  0.002555  0.232065 -1.258925
 2000-01-01 00:00:08 -1.406109 -1.444241 -0.212103
 2000-01-01 00:00:09 -1.132030 -1.148759  0.519794
 2000-01-01 00:00:10 -0.302348 -0.166689  0.063389
 2000-01-01 00:00:11 -0.292032 -0.139349 -0.403801
 2000-01-01 00:00:12 -0.474642 -0.364196 -0.038054
 2000-01-01 00:00:13 -0.727598 -0.645427 -0.453627
 2000-01-01 00:00:14 -0.450036 -0.355256  0.564148
 2000-01-01 00:00:15 -0.112481  0.077858 -0.645291
 2000-01-01 00:00:16 -0.559232 -0.462398 -0.050233
 2000-01-01 00:00:17 -1.488328 -1.514584 -0.989760
 2000-01-01 00:00:18 -1.918189 -2.075466  0.835002
 2000-01-01 00:00:19 -0.817786 -0.772209  0.206960,
 'data3':                           y_1       y_2       y_3
 2000-01-01 00:00:01 -0.181452 -0.124926  0.015228
 2000-01-01 00:00:02 -0.137071 -0.068669 -0.122790
 2000-01-01 00:00:03 -0.052181  0.024470  0.054490
 2000-01-01 00:00:04  0.014752  0.110609 -0.193173
 2000-01-01 00:00:05 -0.174200 -0.110983 -0.152203
 2000-01-01 00:00:06  0.080273  0.172575  0.246322
 2000-01-01 00:00:07  0.001185  0.107597 -0.583699
 2000-01-01 00:00:08 -0.651941 -0.669621 -0.098342
 2000-01-01 00:00:09 -0.524865 -0.532621  0.241002
 2000-01-01 00:00:10 -0.140183 -0.077285  0.029390
 2000-01-01 00:00:11 -0.135400 -0.064609 -0.187222
 2000-01-01 00:00:12 -0.220067 -0.168859 -0.017644
 2000-01-01 00:00:13 -0.337350 -0.299252 -0.210324
 2000-01-01 00:00:14 -0.208659 -0.164714  0.261567
 2000-01-01 00:00:15 -0.052152  0.036099 -0.299188
 2000-01-01 00:00:16 -0.259287 -0.214390 -0.023290
 2000-01-01 00:00:17 -0.690062 -0.702236 -0.458901
 2000-01-01 00:00:18 -0.889367 -0.962288  0.387148
 2000-01-01 00:00:19 -0.379166 -0.358034  0.095957,
 'data6':                             y_1         y_2        y_3
 2000-01-01 00:00:01  -24.923866  -17.159492   2.091650
 2000-01-01 00:00:02  -18.827772   -9.432186 -16.866128
 2000-01-01 00:00:03   -7.167503    3.361151   7.484687
 2000-01-01 00:00:04    2.026274   15.192954 -26.533799
 2000-01-01 00:00:05  -23.927666  -15.244357 -20.906226
 2000-01-01 00:00:06   11.026122   23.704474  33.834240
 2000-01-01 00:00:07    0.162740   14.779270 -80.175653
 2000-01-01 00:00:08  -89.549225  -91.977685 -13.507979
 2000-01-01 00:00:09  -72.094285  -73.159638  33.103496
 2000-01-01 00:00:10  -19.255264  -10.615743   4.036978
 2000-01-01 00:00:11  -18.598285   -8.874552 -25.716433
 2000-01-01 00:00:12  -30.227951  -23.194102  -2.423510
 2000-01-01 00:00:13  -46.337691  -41.104553 -28.889641
 2000-01-01 00:00:14  -28.660901  -22.624761  35.928214
 2000-01-01 00:00:15   -7.163456    4.958464 -41.095860
 2000-01-01 00:00:16  -35.615159  -29.448193  -3.199118
 2000-01-01 00:00:17  -94.785394  -96.457568 -63.033679
 2000-01-01 00:00:18 -122.161436 -132.177754  53.177769
 2000-01-01 00:00:19  -52.081397  -49.178782  13.180422}